[package]
name = "ffsvm"
description="A libSVM compatible support vector machine, but up to 10x faster, for games or VR."
version = "0.6.0"
repository = "https://github.com/ralfbiedert/ffsvm-rust"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.md"
categories = ["science", "algorithms"]
keywords = ["svm", "libsvm", "machine-learning"]
license = "MIT"
edition = "2018"
exclude = [
    "docs/*",
]

[badges]
travis-ci = { repository = "ralfbiedert/ffsvm-rust" }
maintenance = { status = "experimental" }


[dependencies]
simd_aligned = { git = "https://github.com/Tobii/simd_aligned_rust.git" }
# simd_aligned = { path = "../simd_aligned" }
packed_simd = "0.3"
rand = "0.5"
pest = "1.0"
pest_derive = "1.0"

[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib" ]

[profile.release]
opt-level = 3
lto = true
